#!/bin/bash

mkdir -p ../usr/src
mkdir -p ../usr/inc
mkdir -p ../usr/simulink

cp -n test/main.c ..
cp -n test/Makefile ..
cp -n test/.gitignore ..
cp -n test/FreeRTOSConfig.h ../usr/inc
cp -n test/ss_config.h ../usr/inc
 

cd libopencm3
make
cd ../..


ln -s fse_pb_bsp/tools/ss ss

python3 -m venv .venv

source .venv/bin/activate

pip install --upgrade pip

pip install can
pip install click
pip install cryptography
pip install intelhex
pip install cbor
pip install pyyaml
pip install python-can
pip install cantools
pip install telnetlib3


# --- vscode -----------------------------------------------------------------
# regenerated on every init, gitignored. The windows counterpart is written by
# ssw.write_vscode_config(), which points at the STM32CubeCLT gdb server
# instead of openocd.

mkdir -p .vscode

cat > .vscode/launch.json <<'EOF'
// GENERATED by fse_pb_bsp/init.sh - re-run it to refresh.
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Flash + Debug (bp_test)",
            "preLaunchTask": "ss flash",
            "type": "cortex-debug",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "executable": "${workspaceFolder}/build/bp_test.elf",

            // DO NOT set this to program the elf. The application is signed
            // and written by ./ss flash; letting the debugger flash the elf
            // puts an UNSIGNED image into slot0 and mcuboot refuses to boot it.
            "loadFiles": [],

            "servertype": "openocd",
            "configFiles": ["fse_pb_bsp/tools/openocd.cfg"],

            // mcuboot runs first and jumps into slot0, so main is only
            // reached once the bootloader has handed over
            "runToEntryPoint": "main"
        },
        {
            "name": "Debug only (already flashed)",
            "type": "cortex-debug",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "executable": "${workspaceFolder}/build/bp_test.elf",
            "loadFiles": [],
            "servertype": "openocd",
            "configFiles": ["fse_pb_bsp/tools/openocd.cfg"],
            "runToEntryPoint": "main"
        }
    ]
}
EOF

cat > .vscode/tasks.json <<'EOF'
// GENERATED by fse_pb_bsp/init.sh - re-run it to refresh.
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "ss build",
            "type": "shell",
            "command": "${workspaceFolder}/ss",
            "args": ["build"],
            "group": { "kind": "build", "isDefault": true },
            "problemMatcher": ["$gcc"]
        },
        {
            "label": "ss flash",
            "type": "shell",
            "command": "${workspaceFolder}/ss",
            "args": ["flash"],
            "problemMatcher": ["$gcc"]
        },
        {
            "label": "ss clean",
            "type": "shell",
            "command": "${workspaceFolder}/ss",
            "args": ["clean"],
            "problemMatcher": []
        }
    ]
}
EOF

echo "wrote .vscode/launch.json and .vscode/tasks.json"