TGT_CFLAGS += -Ifse_pb_bsp/rtos/include
TGT_CFLAGS += -Ifse_pb_bsp/rtos/portable/GCC/ARM_CM4F
#TGT_CFLAGS += -Ifse_pb_bsp/rtos/CMSIS_RTOS

LIB_OBJS += $(BUILDDIR)/fse_pb_bsp/rtos/tasks.o
LIB_OBJS += $(BUILDDIR)/fse_pb_bsp/rtos/queue.o
LIB_OBJS += $(BUILDDIR)/fse_pb_bsp/rtos/list.o
LIB_OBJS += $(BUILDDIR)/fse_pb_bsp/rtos/timers.o
LIB_OBJS += $(BUILDDIR)/fse_pb_bsp/rtos/event_groups.o
LIB_OBJS += $(BUILDDIR)/fse_pb_bsp/rtos/stream_buffer.o

# Heap (wähle genau eine!)
LIB_OBJS += $(BUILDDIR)/fse_pb_bsp/rtos/portable/MemMang/heap_4.o

# Port für STM32F4 (Cortex-M4 mit FPU)
LIB_OBJS += $(BUILDDIR)/fse_pb_bsp/rtos/portable/GCC/ARM_CM4F/port.o


TGT_CFLAGS += -DSS_USE_RTOS
TGT_CXXFLAGS += -DSS_USE_RTOS

