#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
echo $SCRIPT_DIR

PYTHON="python3"
if [ -x "$SCRIPT_DIR/.venv/bin/python3" ]; then
    PYTHON="$SCRIPT_DIR/.venv/bin/python3"
fi

cd "$SCRIPT_DIR/fse_pb_bsp/tools"
"$PYTHON" "$SCRIPT_DIR/fse_pb_bsp/tools/ss.py" "$@"
